export const KOSHUNPAY_ABI = [
  "function owner() view returns (address)",
  "function paymentToken() view returns (address)",
  "function gosAddress() view returns (address)",
  "function transferOwnership(address newOwner)",
  "function setGosAddress(address newGosAddress)",
  "function isGuide(address) view returns (bool)",
  "function isTourist(address) view returns (bool)",
  "function tourCount() view returns (uint256)",
  "function orderCount() view returns (uint256)",
  "function guideBalance(address) view returns (uint256)",
  "function gosBalance() view returns (uint256)",
  "function reserveBalance() view returns (uint256)",
  "function getGuides() view returns (address[])",
  "function getGuideTourIds(address) view returns (uint256[])",
  "function getPendingOrderIds() view returns (uint256[])",
  "function getUserOrderIds(address) view returns (uint256[])",
  "function getMyActiveBookedOrderIds(address) view returns (uint256[])",
  "function getTour(uint256) view returns (address,string,string,string,string,uint256,uint64,uint32,uint32,bool)",
  "function getOrder(uint256) view returns (uint256,address,address,uint256,uint64,uint64,uint8,bool,bool,uint8)",
  "function createTour(string,string,string,string,uint256,uint32) returns (uint256)",
  "function pay(uint256) returns (uint256)",
  "function confirmPayment(uint256)",
  "function confirmAll(uint256) returns (uint256)",
  "function openDispute(uint256)",
  "function resolveDispute(uint256,bool)",
  "function refund(uint256)",
  "function transferBooking(uint256,address)",
  "function withdrawGuide()",
  "function withdrawGos()",
  "function withdrawReserve()",
  "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
  "event GosAddressChanged(address indexed previousGos, address indexed newGos)",
  "event GuideRegistered(address indexed guide)",
  "event TourCreated(uint256 indexed tourId, address indexed guide, uint256 price, uint64 deadline, uint32 seatsTotal)",
  "event PaymentReceived(uint256 indexed orderId, uint256 indexed tourId, address indexed tourist, uint256 amount, uint64 releaseTime)",
  "event PaymentDistributed(uint256 indexed orderId, uint256 indexed tourId, address indexed tourist, address guide, uint256 totalAmount, uint256 guideAmount, uint256 gosAmount, uint256 reserveAmount)",
  "event DisputeOpened(uint256 indexed orderId, uint256 indexed tourId, address indexed tourist)",
  "event DisputeResolved(uint256 indexed orderId, uint8 status)",
  "event RefundExecuted(uint256 indexed orderId, address indexed tourist, uint256 amount)",
  "event BookingTransferred(uint256 indexed orderId, uint256 indexed tourId, address indexed from, address to)",
  "event Withdrawn(address indexed beneficiary, uint256 amount)"
];
